camunda/zeebe-chaos

- chaos-experiments/kubernetes/scripts/corruptFollowers.sh
- chaos-experiments/kubernetes/scripts/corruptSnapshot.sh
- chaos-experiments/kubernetes/snapshot-corruption/experiment.json
**Description**
The experiment corrupts the snapshot on followers and restart the leader.
The expectation is that the followers can't become leader and the old leader needs to be become leader again.
After that happen the partition should be healthy again and we can create new instances.
**Experiment**
Run the experiment successfully :tada: 
Output:
```
(chaostk) [zell kubernetes/ ns:zell-chaos]$ chaos run snapshot-corruption/experiment.json 
[2020-04-24 13:33:21 INFO] Validating the experiment's syntax
[2020-04-24 13:33:21 INFO] Experiment looks valid
[2020-04-24 13:33:21 INFO] Running experiment: Zeebe can recover from corrupted snapshots
[2020-04-24 13:33:21 INFO] Steady state hypothesis: Zeebe is alive
[2020-04-24 13:33:21 INFO] Probe: All pods should be ready
[2020-04-24 13:33:22 …
```
> Experiment for snapshot corruption

- chaos-experiments/scripts/publish-message.sh
The json returned by `zbctl publish message` contains a key property whose value is a string (not a number). So, it has quotes around it's value, which need to be stripped before the partitionId can be extracted from the key (using a bitshift).
This PR fixes this problem by stripping any non-digit character from the keyString value.
> fix(script): strip quotes from message key

- chaos-days/docusaurus.config.js
- chaos-days/node_modules/.package-lock.json
- chaos-days/package-lock.json
- chaos-days/package.json
The images with the charts are quite cool but they are quite small, unless they are opened in a dedicated window.
This makes the images clickable, which will zoom the image in fullscreen.
This uses this plugin: https://github.com/flexanalytics/plugin-image-zoom
> Images are now zoomable

- .github/workflows/build.yml
- chaos-days/node_modules/.package-lock.json
- chaos-days/package-lock.json
- chaos-days/package.json
It tried to access a Git repository (not published on the npm registry) with the git+ssh protocoal, without having a usable SSH key.
This now uses the (unauthenticated) HTTPS protocol.
It also tries to build the project beforehand, which should show the failure earlier.
> Fix the documentation build on GitHub Actions

- chaos-workers/chaos-worker/src/main/kotlin/io/zeebe/chaos/ReadChaosExperimentsHandler.kt
- chaos-workers/chaos-worker/src/main/kotlin/io/zeebe/chaos/chaosMain.kt
- chaos-workers/chaos-worker/src/main/resources/chaos-experiments
- chaos-workers/chaos-worker/src/test/kotlin/io/zeebe/chaos/ReadChaosExperimentsHandlerTest.kt
Previously it was expected that the worker is run in a specific
location where the git repo (zeebe-chaos) is located nearby and
the worker can access the experiments. This meant that we had
to clone on docker build and pull the repository in the
application. This has now changed.
* The experiments are now symlinked in the resources folder, which caused to copy them into the jar.
* The job handler can easily access the experiments. The handler code is extracted into an own class.
* More error handling is added to the job handler. Non existing
clusterplan or non existing experiments are handled.
* Add additionaly unit tests for the job handler
closes #78
> refactor: bundle experiments in jar

- chaos-workers/chaos-worker/src/main/kotlin/io/zeebe/chaos/WorkerDeploymentFileResolver.kt
- chaos-workers/chaos-worker/src/main/kotlin/io/zeebe/chaos/chaosMain.kt
- chaos-workers/chaos-worker/src/test/kotlin/io/zeebe/chaos/PrepareForChaosExperimentsTest.kt
Resolve the worker deployment from the jar, instead of relying on the git repo.
> refactor: resolve worker deployment

- chaos-workers/chaos-experiments/helm/runChaos.sh
Without setting the namespace, running any experiment will fail:
```
[2022-01-31 14:13:39 DEBUG] [process:52] Running: ['/home/ole/Source/zeebe-chaos/chaos-workers/chaos-experiments/helm/../scripts/shutdown-gracefully-partition.sh', 'Follower', '3']
[2022-01-31 14:13:39 WARNING] [process:70] This process returned a non-zero exit code. This may indicate some error and not what you expected. Please have a look at the logs.
[2022-01-31 14:13:39 DEBUG] [activity:205]   => succeeded with '{'status': 1, 'stdout': '', 'stderr': '+ source utils.sh\n++ CHAOS_SETUP=helm\n+ state=Follower\n+ partition=3\n++ getNamespace\n/home/ole/Source/zeebe-chaos/chaos-workers/chaos-experiments/helm/../scripts/utils.sh: line 8: NAMESPACE: unbound variable\n+ namespace=\n'}'
```
> Set namespace when using helm

- chaos-workers/chaos-experiments/scripts/verify-readiness.sh
We can use the deployment for `kubectl wait`. The check fails if all pods in the deployment are ready.
closes https://github.com/zeebe-io/zeebe-cluster-testbench/issues/568
> fix: verify gateway pods are ready using deployment

- chaos-workers/chaos-experiments/scripts/utils.sh
- chaos-workers/chaos-experiments/scripts/verify-readiness.sh
When gateway pods are evicted, they stay around with status "Shutdown".
We need to filter for running pods to get a gateway that we can actually use.
> fix: don't try to use shutdown gateways

- go-chaos/cmd/publish.go
- go-chaos/cmd/root.go
- go-chaos/internal/zeebe.go
- go-chaos/internal/zeebe_test.go
Adds a new feature to publish a message with a printable correlation key to an specific (given) partition. This is useful if we want to experiment with message correlation, for example disconnect certain partitions etc.
```go
// The message publish partition distribution is based
// on the following hashcode and modulo by the partition count
//
// Since this calculation is used not only on publish, but also for
// opening the message and instance subscriptions we must support for
// backwards compatibility, otherwise message will not be correlated
//
// This allows us to make certain assumptions, and shortcuts.
//
// static int getSubscriptionHashCode(final DirectBuffer correlationKey) {
//   is equal to java.lang.String#hashCode
//   int hashCode = 0;
//
//   for (int i = 0, length = …
```
> Publish message on specific partition

- go-chaos/cmd/backup.go
- go-chaos/cmd/disconnect.go
- go-chaos/cmd/publish.go
- go-chaos/cmd/restart.go
- go-chaos/cmd/terminate.go
- go-chaos/cmd/topology.go
- go-chaos/cmd/verify.go
- go-chaos/internal/pods.go
This adds two commands that allow taking a backup and waiting for a backup to complete or fail
> feat: add `backup take` and `backup wait` commands

- .github/workflows/publishZbchaosImage.yml
- go-chaos/deploy/deployment.yaml
I've already created the secrets and deployed on both prod and dev namespaces.
This also fixes the workflow that publishes the zbchaos image on releases.
closes #199
> feat: deployment manifests for zbchaos worker

- go-chaos/cmd/root.go
- go-chaos/cmd/worker.go
- go-chaos/internal/flags.go
- go-chaos/internal/zeebe.go
Previously the client created inside a command to connect to a cluster was always using `UsePlaintextConnection=true`. This would not work with the clusters in ultrachaos. Testbench already passes the credentials via variables. This PR uses that credentials to access the cluster under test.
Manually tested this by running `zbchaos restart --namespace......` against a cluster running in ultrachaos. Also tested against a cluster in our benchmark cluster which requires insecure connection. Both works. Have not tested the zbchaos worker yet, because that would require deploying a new image with this changes. I will test it after merging this PR. 
closes #220
> feat: commands use provided credentials to connect to the cluster under test

- .github/workflows/publishZbchaosImage.yml
Previously dependabot PR's always fail, since the zbchaos docker build fails. The action has no access to the related secrets when dependabot creates an PR.
> Ignore dependabot PR's

- go-chaos/cmd/backup.go
- go-chaos/cmd/worker.go
- go-chaos/internal/cluster.go
- go-chaos/internal/helper_test.go
- go-chaos/internal/k8helper.go
- go-chaos/internal/labels.go
This PR adds `backup setup` and `backup restore` commands and fix a couple of issues found while testing.
> feat: add command that can restore a cluster from a backup id

- go-chaos/internal/deployment.go
- go-chaos/internal/deployment_test.go
- go-chaos/internal/flags.go
- go-chaos/internal/helper_test.go
- go-chaos/internal/k8helper.go
- go-chaos/internal/labels.go
- go-chaos/internal/network_test.go
- go-chaos/internal/pods.go
- go-chaos/internal/pods_test.go
- go-chaos/internal/saas.go
- go-chaos/internal/saas_test.go
- go-chaos/internal/statefulset.go
- go-chaos/internal/statefulset_test.go
Introduce a new saas flag to simplify code and make it clearer when to use what. This allows to avoid to do multiple calls, like first checking whether brokers pods with self-managed label are deployed and then with SaaS label. With this approach we can know in which environment we are running.
Adjust the tests to also use the CRD to detect the environment.
> Introduce new SaaS flag

- go-chaos/cmd/connect.go
- go-chaos/cmd/disconnect.go
- go-chaos/internal/network.go
- go-chaos/internal/network_test.go
- go-chaos/internal/pods.go
- go-chaos/internal/pods_test.go
blocked by #232 
- Allow to disconnect first gateway with broker of specific nodeId or partitionId and role.
- Allow to disconnect first gateway with all brokers.
- Allow to disconnect only one direction (asymetric)
- Allow to connect all again
Features are similar or more than:
* https://github.com/zeebe-io/zeebe-chaos/blob/main/chaos-workers/chaos-experiments/scripts/disconnect-standalone-gateway.sh
* https://github.com/zeebe-io/zeebe-chaos/blob/main/chaos-workers/chaos-experiments/scripts/connect-standalone-gateway.sh
Note: right now we only support disconnecting the first standalone gateway, this was how we did it before as well. We can improve that later.
closes #225 
-----
Example usage:
```
$ ./zbchaos disconnect gateway
Disconnect zell-chaos-zeebe-gateway-7c4f86f95f-2kp24 from …
```
> Support disconnect gateway within zbchaos

- go-chaos/cmd/deploy.go
- go-chaos/cmd/root.go
- go-chaos/internal/bpmn/multi-version/fancyDecision_v2.dmn
- go-chaos/internal/zeebe.go
Add new sub command `deploy process` to deploy process models, either specified by the user
via `--processModelPath` or if not given it will deploy multiple versions of default models (BPMN and DMN).
The user is able to specify the count of versions which should be deployed for each.
This allows experimenting with deployment distribution.
Replacement of:
-  deploy-different-versions.sh
-  deploy-model.sh
-  deploy-specific-model.sh
closes https://github.com/zeebe-io/zeebe-chaos/issues/226
closes https://github.com/zeebe-io/zeebe-chaos/issues/160
```
$ ./zbchaos deploy process --verbose         
Connecting to zell-chaos
Successfully created port forwarding tunnel
Deploy 10 versions of different type of models.
Deployed [2/10] versions.
Deployed [4/10] versions.
Deployed [6/10] versions. …
```
> Deploy models via zbchaos

- go-chaos/cmd/deploy.go
- go-chaos/internal/deployment.go
- go-chaos/internal/deployment_test.go
- go-chaos/internal/manifests/worker.yaml
Add new sub-command to deploy Zeebe workers into a Zeebe cluster, which can be used for several chaos experiments. This allows completing process instances etc.
closes https://github.com/zeebe-io/zeebe-chaos/issues/235
--------
**Example:**
Non-verbose: Deploy worker:
```sh
$ ./zbchaos deploy worker
Worker successfully deployed to the current namespace: zell-chaos
```
Verbose: Deploy worker
```sh
$ ./zbchaos deploy worker -v
Connecting to zell-chaos
Running experiment in self-managed environment.
Deploy worker deployment to the current namespace: zell-chaos
Worker successfully deployed to the current namespace: zell-chaos
```
```sh
$ k get deployments.apps 
NAME                       READY   UP-TO-DATE   AVAILABLE   AGE
worker                     3/3     3            3           107s
``` …
> Allow to deploy Zeebe workers with zbchaos

- go-chaos/cmd/verify.go
- go-chaos/internal/fake.go
- go-chaos/internal/zeebe.go
- go-chaos/internal/zeebe_test.go
Allows creating a process instance for a specific version and BPMN process id via the verify steady-state command.
This is useful for the deployment distribution command.
Furthermore, I also created the first version of a Zeebe Fake client, in order to intercept values which are set on the client requests. This allows us to create more unit tests where we can verify whether the right properties and values are set.
Added some new tests for the process instance creation via version and BPMN process id.
closes https://github.com/zeebe-io/zeebe-chaos/issues/244
-----
**Example:**
Deploy model
```sh
$ ./zbchaos deploy process -v
Connecting to zell-chaos
Running experiment in self-managed environment.
Successfully created port forwarding tunnel
Deploy 10 versions of different type of models. …
```
> Create process instance for specific version

- go-chaos/cmd/restart.go
- go-chaos/cmd/terminate.go
- go-chaos/internal/pods.go
Extend the restart method to specify the gracePeriod allows to extract logic and reuse methods in restart and terminate commands.
Reduces several code duplications.
> Refactor the terminate/restart commands

- go-chaos/Dockerfile
- go-chaos/backend/connection.go
- go-chaos/cmd/connect.go
- go-chaos/cmd/disconnect.go
- go-chaos/cmd/stress.go
* I extracted code from connect and disconnect to  a new package, backend. 
* The code was refactored such it returns errors, instead of doing panic. Panic is done in commands currently.
I thought I can reuse the code and call it in an extra worker, but the problem I see is the argument parsing. I would need to do it for everything again somehow.
I realized that the for each command an `RunE` can be set instead of `Run` which allows to return an error. This would be useful for the zbchaos worker, since when now executing a command it would return an error instead of panicking. 
Wdyt @oleschoenburg does this look like a solution for you? Would like to get your opinion. I did that as example in the last commit.
I need to run this as cli locally to try it out how it behaves then.
> Refactor Backend

- go-chaos/backend/clients.go
- go-chaos/backend/connection.go
- go-chaos/cmd/deploy.go
- go-chaos/internal/bpmn/chaos/actionRunner.bpmn
- go-chaos/internal/bpmn/chaos/chaosExperiment.bpmn
- go-chaos/internal/bpmn/chaos/chaosToolkit.bpmn
- go-chaos/internal/zeebe.go
Allows to bundle the chaos experiments with zbchaos and deploy them via `zbchaos deploy chaos` command.
This simplifies the testing of them and we can use that in the k8 deployment to first deploy the models and then start the worker.
> Deploy chaos process models

- go-chaos/cmd/worker.go
- go-chaos/worker/chaos_worker.go
- go-chaos/worker/chaos_worker_test.go
- go-chaos/worker/fake.go
* Move logic of worker into own package.
* For better encapsulation and testability
* Write new tests for job worker/handler
> New tests for worker

- go-chaos/cmd/dataloss_sim.go
- go-chaos/internal/dataloss_sim_helper.go
- go-chaos/internal/pods.go
When recovering after dataloss, there might be other brokers which are not yet recovered. So we cannot wait for all brokers to be ready.
> fix: Do not wait for all pods to be ready in dataloss recovery

- go-chaos/cmd/worker.go
> fix: use correct handle method

- go-chaos/Dockerfile
- go-chaos/cmd/worker.go
Turn on json logging for worker docker image, so we have better logging output
> Enable json logging for worker

- go-chaos/internal/chaos-experiments/chaos_experiments.go
- go-chaos/internal/chaos-experiments/chaos_experiments_test.go
Set json annotation to marshal the experiments into correct key, with small letters.
> Experiments need to start with lower letter

- .github/workflows/publishZbchaosImage.yml
This is useful for testing and no need to wait until the release. The image is not tagged as SNAPSHOT but with the commit sha.
> ci: build a snapshot image of zbchaos

- go-chaos/cmd/disconnect.go
- go-chaos/integration/integration_test.go
- go-chaos/internal/chaos-experiments/camunda-cloud/production-s/deployment-distribution/experiment.json
- go-chaos/internal/network.go
- go-chaos/worker/chaos_worker.go
Based on #267 (blocked by)
related to https://github.com/zeebe-io/zeebe-chaos/issues/237
-------
**Fixed some smaller issues, like:**
*  rm one-direction from mutex
* make possible to run workers against self-managed clusters
* return correct errors on connect
**Migrate the Deployment distribution experiment, as the first experiment, to zbchaos.**
The experiment was executed and verified via the integration test against a self-managed cluster.
I moved the experiment into the `chaos-experiments/camunda-cloud/test/` folder and migrated it, with that approach I was able to execute the experiment with `eze` and running against my self-managed `zell-chaos` zeebe cluster.
Log output:
```
Deploy file bpmn/chaos/actionRunner.bpmn (size: 8788 bytes).
Deployed process model …
```
> Migrate Deployment distribution experiment

- go-chaos/cmd/deploy.go
- go-chaos/cmd/root.go
- go-chaos/internal/chaos-experiments/camunda-cloud/production-s/deployment-distribution/experiment.json
- go-chaos/internal/chaos-experiments/camunda-cloud/production-s/follower-restart/experiment.json
- go-chaos/internal/zeebe.go
- go-chaos/worker/chaos_worker.go
:white_check_mark: Depends on #268 
related to https://github.com/zeebe-io/zeebe-chaos/issues/237
------------
Migrates the follower restart experiment and tested with integration test
Log output:
```
Deploy file bpmn/chaos/actionRunner.bpmn (size: 8788 bytes).
Deployed process model bpmn/chaos/actionRunner.bpmn successful with key 2251799813685249.
Deploy file bpmn/chaos/chaosExperiment.bpmn (size: 21403 bytes).
Deployed process model bpmn/chaos/chaosExperiment.bpmn successful with key 2251799813685251.
Deploy file bpmn/chaos/chaosToolkit.bpmn (size: 11031 bytes).
Deployed process model bpmn/chaos/chaosToolkit.bpmn successful with key 2251799813685253.
Create ChaosToolkit instance
Open workers: [zbchaos, readExperiments].
Handle read experiments job [key: 2251799813685265]
Read …
```
> Migrate follower restart experiment

- go-chaos/internal/chaos-experiments/camunda-cloud/production-s/follower-terminate/experiment.json
depends #269 
related to https://github.com/zeebe-io/zeebe-chaos/issues/237
-----
Migrates the follower terminate experiment and tested with integration test
Log output:
```
Deploy file bpmn/chaos/actionRunner.bpmn (size: 8788 bytes).
Deployed process model bpmn/chaos/actionRunner.bpmn successful with key 2251799813685249.
Deploy file bpmn/chaos/chaosExperiment.bpmn (size: 21403 bytes).
Deployed process model bpmn/chaos/chaosExperiment.bpmn successful with key 2251799813685251.
Deploy file bpmn/chaos/chaosToolkit.bpmn (size: 11031 bytes).
Deployed process model bpmn/chaos/chaosToolkit.bpmn successful with key 2251799813685253.
Create ChaosToolkit instance
Open workers: [zbchaos, readExperiments].
Handle read experiments job [key: 2251799813685265]
Read experiments successful, complete job …
```
> Migrate follower terminate

- go-chaos/integration/integration_test.go
- go-chaos/internal/chaos-experiments/camunda-cloud/production-s/follower-terminate/experiment.json
- go-chaos/internal/chaos-experiments/camunda-cloud/production-s/leader-restart/experiment.json
- go-chaos/internal/chaos-experiments/camunda-cloud/test/integration/experiment.json
blocked by #269 
blocked by #270 
related to #237 
------
Migrated the leader restart experiment to the zbchaos toolkit
Log output:
```
Deployed process model bpmn/chaos/actionRunner.bpmn successful with key 2251799813685249.
Deploy file bpmn/chaos/chaosExperiment.bpmn (size: 21403 bytes).
Deployed process model bpmn/chaos/chaosExperiment.bpmn successful with key 2251799813685251.
Deploy file bpmn/chaos/chaosToolkit.bpmn (size: 11031 bytes).
Deployed process model bpmn/chaos/chaosToolkit.bpmn successful with key 2251799813685253.
Create ChaosToolkit instance
Open workers: [zbchaos, readExperiments].
Handle read experiments job [key: 2251799813685265]
Read experiments successful, complete job with: {"experiments":[{"contributions":{"availability":"high","reliability":"high"},"description":" …
```
> Migrate leader restart

- go-chaos/internal/chaos-experiments/camunda-cloud/production-s/broker-dataloss/experiment.json
After a broker recovered from loss of disk, cluster should be able to survive another broker's disk loss. After a series of loss of disk of one broker at a time, the cluster should not suffer dataloss. We verify this by creating instances of the process that is deployed before the disk loss.
In this we don't have to call `zbchaos dataloss prepare` because there is no need to add init containers. Since we are only deleting one broker at a time, the pod can be immediately restarted.
related to #4
> feat: verify cluster can survive dataloss of one broker at a time.

- go-chaos/cmd/root.go
- go-chaos/integration/integration_test.go
- go-chaos/internal/logging.go
- go-chaos/worker/chaos_worker.go
- go-chaos/worker/chaos_worker_test.go
NEW
Add a logging context, which can be set by the workers to enrich our json logs with more useful information, like process instance key, experiment title etc.
The context is set at the begin of the run zbchaos handler and removed again. See https://github.com/zeebe-io/zeebe-chaos/pull/273#issuecomment-1340664349
-----------
OLD
Add a new parameter `--loggingContext` to the root command to set the logging context. 
This is used by the workers to enrich the logging with details like processInstanceKey, experiment name, etc. This is really useful for debugging since we can group and filter the logging better in stackdriver.
Adjust the tests related to that. Furthermore add a test to verify that the worker can also run without clusterId, which I use in my local tests.
Integration test …
> Add logging context

- go-chaos/internal/chaos-experiments/camunda-cloud/production-s/multiple-leader-restart/experiment.json
related to #237 
Similar to the other migrated experiments I followed same approach as described here https://github.com/zeebe-io/zeebe-chaos/pull/268
> The experiment was executed and verified via the integration test against a self-managed cluster.
> 
> I moved the experiment into the chaos-experiments/camunda-cloud/test/ folder and migrated it, with that approach I was able to execute the experiment with eze and running against my self-managed zell-chaos zeebe cluster.
> feat: migrate multi leader restart

- go-chaos/internal/chaos-experiments/camunda-cloud/production-s/stress-cpu-on-broker/experiment.json
related to #237 
Similar to the other migrated experiments I followed same approach as described here https://github.com/zeebe-io/zeebe-chaos/pull/268
> The experiment was executed and verified via the integration test against a self-managed cluster.
> 
> I moved the experiment into the chaos-experiments/camunda-cloud/test/ folder and migrated it, with that approach I was able to execute the experiment with eze and running against my self-managed zell-chaos zeebe cluster.
```
Create ChaosToolkit instance
Open workers: [zbchaos, readExperiments].
Handle read experiments job [key: 2251799813685265]
Read experiments successful, complete job with: {"experiments":[{"contributions":{"availability":"high","reliability":"high"},"description":"This fake experiment is just to test the integration …
```
> Migrate stress cpu

- go-chaos/internal/chaos-experiments/camunda-cloud/production-s/worker-restart/experiment.json
- go-chaos/internal/deployment.go
- go-chaos/internal/deployment_test.go
First fixed an issue with the worker deployments:
In self-managed env the zeebe gateway service is called differently, based on the helm release name.
The release name is in our setups normally also the namespace name, which we use here.
If the worker is already deployed we update the deployment, instead of failing.
+ Added missing tests for it.
Migrated the worker restart experiment related to #237 
Similar to the other migrated experiments I followed same approach as described here https://github.com/zeebe-io/zeebe-chaos/pull/268
> The experiment was executed and verified via the integration test against a self-managed cluster.
> 
> I moved the experiment into the chaos-experiments/camunda-cloud/test/ folder and migrated it, with that approach I was able to execute the experiment with …
> Migrate worker restart experiment

- go-chaos/internal/helper_test.go
- go-chaos/internal/pods.go
- go-chaos/internal/pods_test.go
Observed that the ready status = true when the pod is terminating.
> fix: for readiness check both the phase and ready status

- go-chaos/internal/helper_test.go
- go-chaos/internal/pods.go
- go-chaos/internal/pods_test.go
> Cleanup and reduce test duration

- go-chaos/cmd/verify.go
- go-chaos/cmd/worker.go
- go-chaos/deploy/deployment.yaml
- go-chaos/internal/chaos-experiments/camunda-cloud/production-s/worker-restart/experiment.json
- go-chaos/internal/zeebe.go
- go-chaos/internal/zeebe_test.go
During deploying and running zbchaos with our QA runs we encountered several issues which I fix in this PR.
When deploying zbchaos and on the zbchaos worker we need to use different names for the environment variables.
When we using the normal ZEEBE_ environment variables we run into conflicts with using multiple zeebe clients, the env vars will always overwrite direct values.
When setting the credentials provider we also have to set the UsePlainText to false.
We need no credentials when running against the target cluster since we port forward to the gateway. This means we can remove the credentials usage.
The awaiting of the process instances doesn't require the partition id check. Moreover, this is problematic for things like message correlation since a message is correlated only once …
> Multiple zbchaos fixes

- go-chaos/backend/connection.go
- go-chaos/cmd/backup.go
- go-chaos/cmd/connect.go
- go-chaos/cmd/dataloss_sim.go
- go-chaos/cmd/deploy.go
- go-chaos/cmd/disconnect.go
- go-chaos/cmd/exporting.go
- go-chaos/cmd/publish.go
- go-chaos/cmd/restart.go
- go-chaos/cmd/root.go
- go-chaos/cmd/stress.go
- go-chaos/cmd/terminate.go
- go-chaos/cmd/topology.go
- go-chaos/cmd/verify.go
- go-chaos/cmd/version.go
- go-chaos/cmd/worker.go
- go-chaos/cmd/zeebePods.go
- go-chaos/internal/flags.go
- go-chaos/internal/k8helper.go
- go-chaos/internal/k8helper_test.go
In order to not run into issues with global variables reused and reset during worker execute, we encapsulated all commands and make it available via `NewCMD` so everytime we have to create a new command to execute zbchaos in the workers. 
This allows us to always use a clean context.
> Encapsulate all commands

- go-chaos/cmd/root.go
- go-chaos/worker/chaos_worker.go
* enable higher precision for the logging timestamp. Previously we had the issue that the logs were not correctly sorted, since the timestamp were the same.
* always enable json and verbose logging in worker
> Improve worker logging

- go-chaos/integration/integration_test.go
Increase the timeout in the IT tests, so it can also be used for running all chaos experiments.
> fix: increase timeout

- go-chaos/internal/chaos-experiments/camunda-cloud/production-s/stress-cpu-on-broker/experiment.json
Previously we encountered several issues due to putting stress on broker, since this causes leader changes and then the deployment will not work. We should wait for a while and then try to verify the steady state
> fix: add pause after stress

- go-chaos/internal/bpmn/chaos/chaosToolkit.bpmn
Removes an unnecessary I/O mapping when an experiment fails. This triggered an incident in Testbench because there is no variable source. It also doesn't seem to me like this was required at all.
Other changes were due to me using a much newer version of the modeler.
> fix: remove unnecessary I/O mapping

- go-chaos/internal/volume.go
Reclaim policy of pvc is "Delete", which means it will be automatically deleted when PV is deleted and it is no longer attached to a pod. 
When we delete both PVC and PV together, PV is not getting deleted. We don't know yet why this happens. But we (with @multani ) verified that when we delete PVC, the PV is also getting deleted.
https://github.com/camunda-cloud/team-sre/issues/253#issuecomment-1609259799
> fix: only delete pvc

- go-chaos/cmd/root.go
Flags have been printed even on non-verbose mode, which was confusing.
> fix: remove flags logging (non-verbose)

- go-chaos/go.mod
- go-chaos/go.sum
- go-chaos/internal/network.go
- go-chaos/internal/stress.go
Since https://github.com/camunda/zeebe/pull/13418 got merged the zeebe container runs with an unprivileged `zeebe` user.
As the chaos tooling makes use of apt to install some tools needed to e.g. stress the cpu or modify ip routes we need to also overwrite the `runAsUser` to root to make that possible still.
Unfortnately the k8s exec API is not offering a way to override the user see https://github.com/kubernetes/kubectl/blob/master/pkg/cmd/exec/exec.go#L104
The first commit resolves an issue that lead to test failure, see https://github.com/testcontainers/testcontainers-go/issues/1359#issuecomment-1657098312
> fix(setup): runAs root to install tooling

- go-chaos/cmd/publish.go
Messages were published with a TTL of 5 minutes, which means the engine buffers them for 5 minutes. The buffered message is then expected to correlate to a process instance's event later in the chaos experiment.
However, in some cases, the chaos experiment takes longer than these 5 minutes. When the message is expired, the chaos experiment can no longer succeed even though it retries for an hour. For example, this occurred in the action:
- Should be able to create a process instance and await the message correlation
Changing the TTL of the published message fixes this problem by buffering the message for the same duration as the retry period.
> fix: publish message with 1h ttl

- .github/workflows/publishZbchaosImage.yml
- .github/workflows/release.yaml
I don't want to follow the manual guide anymore.
This PR adds a new workflow which allows to manually trigger zbchaos release, following the guide documented in the README https://github.com/zeebe-io/zeebe-chaos/blob/zbchaosv1.3.0/go-chaos/README.md
What is missing to autodeploy the zbchaos docker image, after it is created by the other github action. But step by step.
Resources:
* https://docs.github.com/en/actions/using-workflows/using-github-cli-in-workflows
* https://github.com/zeebe-io/zeebe-chaos/blob/zbchaosv1.3.0/go-chaos/README.md
* https://github.blog/changelog/2020-07-06-github-actions-manual-triggers-with-workflow_dispatch/
> Add release workflow

- go-chaos/internal/labels.go
- go-chaos/internal/labels_test.go
See [slack](https://camunda.slack.com/archives/C013MEVQ4M9/p1697628052664839).
This aligns the labels to the change done with https://github.com/camunda-cloud/camunda-operator/pull/2032/files
> fix: use new app label for zeebe gateway saas

- go-chaos/internal/saas.go
We currently silently hide errors on detecting the SaaS environment, this PR should at least log them.
> refactor: add error logging for detecting saas env

- go-chaos/cmd/deploy.go
- go-chaos/cmd/root.go
- go-chaos/integration/integration_test.go
- go-chaos/internal/deployment.go
- go-chaos/internal/deployment_test.go
- go-chaos/internal/manifests/worker.yaml
- go-chaos/worker/chaos_worker.go
- go-chaos/worker/chaos_worker_test.go
Allow to specify a dockerImageTag as global parameter, to be used by the deployed worker (and maybe later starter, etc.)
This is to make sure that we use the same client version as the deployed/target zeebe cluster.
closes https://github.com/zeebe-io/zeebe-chaos/issues/446
> Use docker image for the workers

- go-chaos/cmd/restart.go
- go-chaos/cmd/terminate.go
Adds a new `--all` flag to the `restart broker` command, e.g. `zbchaos restart broker --all` which will restart all brokers in the current namespace.
> feat: allow restarting all brokers

- go-chaos/cmd/deploy.go
- go-chaos/cmd/root.go
- go-chaos/internal/deployment.go
- go-chaos/internal/deployment_test.go
- go-chaos/internal/manifests/worker.yaml
**Description**
This PR allows injecting the polling delay into the worker deployment. The polling delay is given via command line as milliseconds because I couldn't be bothered to figure out how to convert to a nicer type from string :upside_down_face: 
This will now allow us to "disable" polling for job push experiments.
It also fixes setting a default value for the worker Docker image tag, as it was previously defaulting to `""` when omitted.
> Allow injecting polling delay into worker deployment

- go-chaos/internal/chaos-experiments/camunda-cloud/job-push-gateway/restart.json
- go-chaos/internal/chaos-experiments/camunda-cloud/job-push-gateway/terminate.json
- go-chaos/internal/chaos-experiments/camunda-cloud/manifest.yml
- go-chaos/internal/chaos-experiments/camunda-cloud/worker-resilience/gateway-restart.json
- go-chaos/internal/chaos-experiments/camunda-cloud/worker-resilience/gateway-terminate.json
- go-chaos/worker/chaos_worker_test.go
**Description**
Adds two new experiments which are for 8.4 only, ensuring job push remains resilient even when gateways are restarted.
Tested manually using the integration test.
closes #442
> Experiment: job worker stream is resilient to gateway crashes

- go-chaos/cmd/cluster.go
- go-chaos/cmd/cluster_test.go
- go-chaos/cmd/root.go
- go-chaos/integration/cluster_cmd_integration_test.go
Adds a new command `zbchaos cluster status` that uses  `GET /actuator/cluster` under the hood and pretty-prints the deserialized response.
Part 1 of X for https://github.com/zeebe-io/zeebe-chaos/issues/458
> feat(zbchaos): query current cluster topology

- go-chaos/internal/manifests/worker.yaml
We need to use the newer java options, in order to configure our application otherwise it will not be picked up.
> fix: use correct JDK_JAVA_OPTIONS

- go-chaos/backend/clients.go
- go-chaos/cmd/backup.go
- go-chaos/cmd/cluster.go
- go-chaos/cmd/deploy.go
- go-chaos/cmd/exporting.go
- go-chaos/cmd/publish.go
- go-chaos/cmd/stress.go
- go-chaos/cmd/terminate.go
- go-chaos/cmd/topology.go
- go-chaos/cmd/verify.go
- go-chaos/internal/pods.go
- go-chaos/worker/chaos_worker.go
All commands now provide `0` as the local port which results in a free port picked at random. This makes it easier to run two zbchaos commands at the same time without getting port conflicts.
> feat(zbchaos): port-forward to random local port

- go-chaos/cmd/cluster.go
- go-chaos/cmd/root.go
- go-chaos/cmd/topology.go
Adds a new command that makes an API call to Zeebe to scale to the given amount of brokers and then scales up the statefulset accordingly. The command knows if it is scaling up or down to scale the statefulset first or last. The command always waits for completion as it can only scale down the statefulset after the change is applied.
Usage:
```
$ zbchaos cluster scale --brokers 5
```
Part 2/X of #458
> feat(zbchaos): add command for broker scaling

- go-chaos/internal/chaos-experiments/camunda-cloud/manifest.yml
- go-chaos/internal/chaos-experiments/camunda-cloud/scaling/broker-scaling.json
Add an experiment to verify that brokers can be scaled up and the processing continues after scaling. To verify processing continues, a message is published to partition 3. After scaling we expect it to be correlated to a new instance. 
The experiment can only be run on Production - S because it assumes a cluster size of 3 and partitions 3. 
I have not tested it. But since we have already manually tested `zbchaos scale` command, I assume this works.
related to https://github.com/camunda/zeebe/issues/15752
> experiment: add experiment for borker-scaling

- go-chaos/cmd/cluster.go
- go-chaos/internal/statefulset.go
While testing E2E test with scaling, noticed that the current `zbchaos cluster scale` command do not work in SaaS because reconciliation is not disabled.
> fix: disable reconciliation before scaling in SaaS

- go-chaos/internal/labels.go
In Helm charts the labels have changed,
adjusting them to correctly match with the stateful set
closes https://github.com/zeebe-io/zeebe-chaos/issues/477
> set correct labels for SM

- go-chaos/internal/helper_test.go
- go-chaos/internal/k8helper.go
- go-chaos/internal/k8helper_test.go
- go-chaos/internal/saas.go
- go-chaos/internal/saas_test.go
Paired with @oleschoenburg on this:
* We agreed on to "simply" pass the error to the front, to the respective commands so they can either fail or do what ever
* For errors indicating resource not-found we decided to return false, and use SM setting (as we expect this CRD not in the SM env)
* We wrote some more tests for the error handling
* I had to refactor a bit the client creation, so we test the right things here
closes #488 
closes #490
> Saas detection error handling

- go-chaos/internal/dataloss_sim_helper.go
- go-chaos/internal/dataloss_sim_helper_test.go
**Description**
Based on the [Slack thread](https://camunda.slack.com/archives/CQZGZ882Z/p1710145484340359?thread_ts=1710144915.404369&cid=CQZGZ882Z) our image registry is changed for int and dev. That causes our chaos tests to fail. This PR is attempting to fix the registry.
> fix: update image registry to correct one

- go-chaos/cmd/cluster.go
- go-chaos/worker/chaos_worker.go
- go-chaos/worker/chaos_worker_test.go
- go-chaos/worker/fake.go
To wait for a scaling operation to completed, we port-forward to a gateway and repeatedly query the status. However, it sometimes failed because the port-forwarding disconnected but it was not retried until the action is retried. By default the actions are retried 3 times. So we have configured a long timeout (around 30 minutes) for the query and wait. That means, when the port-forwarding disconnected the action was still running for 30 minutes, with out a successful query response. If we fail the action early, it might result in an incident because the retries is hard-coded to 3.
Instead, as a generic solution for retries, this PR allows infinite retry of all actions until timeout. This can simplify operations that has to repeatedly query and wait. For example, `verify readiness` or …
> Allow infinite retry of actions until timeout

- go-chaos/internal/helper_test.go
- go-chaos/internal/k8helper.go
- go-chaos/internal/labels.go
- go-chaos/internal/labels_test.go
In SaaS we recently introduced a label that indicates to prevent certain actions (security related), see related [slack thread ](https://camunda.slack.com/archives/CT702EPFH/p1714475896279759)
In order to make sure that our experiments, and actions are successful in SaaS
we need to make sure that reconciliation is paused and the
security enforcement label is removed from the corresponding
target namespace. That is now always done when creating a client for a SaaS environment.
After doing so we can get further privileges, that are needed for
actions like putting stress on the CPU, network partition, etc.
> Remove security enforcement label from namespace in SaaS

- chaos-days/blog/2024-07-25-Using-flow-control-to-handle-bottlenecked-exporting/index.md
This is a slight restructuring and a couple of suggested improvements on top of https://github.com/zeebe-io/zeebe-chaos/pull/535.
1. Use dedicated sections for both experiments instead of mixing them in one.
2. Adjust the example configs to configure only what's needed for each experiment
3. Formatting: newlines after each sentence.
4. Wording: Some general rewording to improve clarity.
I thought opening a PR with suggested improvements is easier than leaving review comments.
If you accept this PR, please apply the same for the second blog post.
> Restructure flowcontrol blog post slightly

- chaos-days/blog/2024-07-25-Using-flow-control-to-handle-bottlenecked-exporting/index.md
- chaos-days/blog/2024-07-25-Using-flow-control-to-handle-uncontrolled-process-loops/index.md
Hey @rodrigo-lourenco-lopes just want to let you know that I added some truncation (would be nice if you could add this on your next post :)) I normally cut after the TL;DR.
This allows to have a nice short view of the blog post in the overview section :)
I did a short screencast of it:
**Without**
**With truncation**
I will go ahead and merge it, I just wanted to let you know :) Thanks again for writing these posts 🚀
> docs: truncate posts

- .github/workflows/go-ci.yml
- go-chaos/go.mod
- go-chaos/go.sum
> Release Policy[¶](https://go.dev/doc/devel/release#policy)
> Each major Go release is supported until there are two newer major releases. For example, 
> Go 1.5 was supported until the Go 1.7 release, and Go 1.6 was supported until the Go 1.8 release.
> 
> https://go.dev/doc/devel/release#:~:text=checkout%20goX.Y.Z-,Release%20Policy,until%20the%20Go%201.8%20release.
Migrating to go1.23.0 (released 2024-08-13)[¶](https://go.dev/doc/devel/release#go1.23.0) as this has been the latest released version.
Locally, when running with Fedora like me, it is often lagging quite far behind. For that we have to manually install the go version like this:
```
$ $ go install golang.org/dl/go1.23.0@latest
$ go1.23.0 
go1.23.0: not downloaded. Run 'go1.23.0 download' to install to …
```
> Migrate to go1.22

- chaos-days/blog/2024-10-24-Camunda-Exporter-MVP/index.md
Fixes list formatting in blog post. I should've done this for Hacktoberfest to get some swag :smile:
> docs: fix formatting of list

- go-chaos/cmd/backup.go
Updates the actuator endpoints to match https://github.com/camunda/camunda/issues/24456
closes #616
> feat: migrate zeebe's backup api from /backups to /backup-runtime

- .github/workflows/release.yaml
Required to release again, otherwise we can't work with our go.mod: https://github.com/camunda/zeebe-chaos/actions/runs/16437984427/job/46453776679
> ci: update go version in release workflow

- go-chaos/internal/zeebe.go
We still port-forward and thus bypass TLS, even if we now use authentication
> fix: still use plaintext connection with authentication

- go-chaos/internal/deployment.go
e507f1f87b2374d2a64dc4d63cf3060cdc8e6cd1 introduced a bug by not reading from the files embedded in the binary.
> fix: read worker template from embedded file

- go-chaos/cmd/cluster.go
This PR makes the chaos‐test client compatible with both pre‑8.6 and post‑8.6 Zeebe clusters by:
* Attempting the new PATCH /actuator/cluster scaling endpoint first
* Falling back to the legacy POST /actuator/cluster/brokers endpoint on a 405 Method Not Allowed
In Zeebe 8.6 the cluster‐scaling actuator was changed from a “GET‐style” URL under `/actuator/cluster/brokers` to a PATCH `/actuator/cluster` endpoint with a richer JSON payload. See related change https://github.com/camunda/camunda/commit/e6a0dc5def76548ce157c5a69ab090bb0a9cb724. Our chaos tests were updated accordingly, but now fail when run against 8.5 brokers (which still only support the old URL/verb).
* Refactor `sendScaleRequest`
* Builds a `ClusterPatchRequest` and calls `sendPatchCluster(...)`
* On success, returns …
> fix: support legacy scaling endpoint for Zeebe <8.6

- go-chaos/cmd/cluster.go
- go-chaos/cmd/cluster_test.go
Fixes a bug introduced with https://github.com/camunda/zeebe-chaos/pull/682 where we were removing brokers from the region that we wanted to failover _to_. We must remove the brokers from the _other_ region instead.
Example of bad behavior before:
```
Running command with args: [--cluster forceFailover --regions=2 --regionId=0] 
Requesting scaling http://localhost:41617/actuator/cluster?force=true with input {"brokers":{"remove":[2,0]},"partitions":null}
```
Here, brokers 0 and 2 are from region 0, we want to remove brokers 1 and 3 instead.
Closes #684
> fix: failover must remove brokers from other region
